import type { Metadata } from "next";
import "@/app/globals.css";
import { interClass, fontClass } from "@/app/fonts";
import Navbar from "@/components/Navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontClass}`}
      >
        
        <Navbar />
        {children}
      </body>
    </html>
  );
}
